name: Deploy
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  compile-site:
    name: Compile Web App to Dist Folder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
    
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      
      - name: Install Global Deps
        run: |
          npm install -g firebase-tools
          npm install -g @angular/cli
          npm install -g tslint
          npm install -g typescript

      - name: Build Functions
        run: |
          cd functions
          npm install
          npm run build
      
#       - name: Build Website
#         run: |
#           cd website
#           npm install
#           npm run build
      
      - name: Deploy to Firebase
        run: |
          firebase --token "${{secrets.FIREBASE_TOKEN}}" use find-help-aa0d5
          firebase --token "${{secrets.FIREBASE_TOKEN}}" deploy
